$(function(){
	$("#content_right").hide()
	$("#login_top_left").click(function(){
		$("#content_left").show()
		$("#content_right").hide()
		$("#login_top_left").css("color","#333333")
		$("#login_top_right").css("color","#AAAAAA")
		$("#login_top_left").removeClass("active");
		$("#login_top_right").addClass("active");
	})
	$("#login_top_right").click(function(){
		$("#content_left").hide()
		$("#content_right").show()
		$("#login_top_left").css("color","#AAAAAA")
		$("#login_top_right").css("color","#333333")
		$("#login_top_right").removeClass("active")
		$("#login_top_left").addClass("active")
	})
});